### ISSUE TITLE
First tests

### ISSUE THREAD

**Issue by Gurigraphics** [ceifa/steamworks.js#1]
Very cool. I did the test. If you want to compare the files I put it in my fork.
I found this error.

File 'SteamClient.ts' replace 'ipcontry' by 'ipcountry'
```js
return await Api.send(`/client/ipcontry` 
```
This I changed only here to use with NW.js 
```js
 process.cwd()
 ```
Instead of
  ```js
  import * as path from 'node:path'
path.resolve(__dirname
 ```
 Sometimes in first run, it doesn't load the lib. However, this probably occurs only here.
   ```js
error Steamworks: Setting breakpad minidump AppID = 480
error Steamworks: SteamInternal_SetMinidumpSteamID:  Caching Steam ID: [API loaded no]
  ```
Steam overlay not yet tested.

I also deleted the Steam dlls because I think sharing this is not allowed.
I know Facepunch.Steamworks shares this, but I think it's illegal.
I recommend leaving in the description the version of the dlls to download on the official website, and in which folder to put it like greenworks repo.

 I also add SteamFriends.cs and SteamFriends.ts to test if I understood how it worked.
 Change It was relatively easy. Calls to the API worked fine. I'll wait now to see the callbacks/events.
I still don't understand 100% of the code, but I really liked it connection js /dotnet. ^^

**Comment by ceifa** [comment]
Hey, thanks a lot for testing, if you want to add your additions PRs are welcome!
If you are still planning to make things(as said in [greenworks#304](https://github.com/greenheartgames/greenworks/issues/304)) you can reach me on discord and we can work together in this project.

**Comment by Gurigraphics** [comment]
Okay. I'll send you a tweet.
