### ISSUE TITLE
GetSubscribedItems?

### ISSUE THREAD

**Issue by tke89** [ceifa/steamworks.js#100]
Hello, I was wondering if there is a way to retrieve a list of the items subscribed to? Or if not, is there a plan to implement? 

Docs say there is a GetSubscribedItems, but couldn't see a a similar function in the declarations file. 

https://partner.steamgames.com/doc/api/ISteamUGC#GetSubscribedItems  

(As an aside, thank you for your work on this. Stellar work.)

**Comment by podrivo** [comment]
@tke89 It was recently included! Make sure to use version 0.2.2 or up
