### ISSUE TITLE
Error: access denied. code: 'Generic Failure' when calling updateItem() with previewPath and contentPath.

### ISSUE THREAD

**Issue by arepp23** [ceifa/steamworks.js#107]
Steps to reproduce:

```
client.workshop
      .updateItem(item.itemId, {
        title: "Red Dot",
        description: "A red dot sight",
        visibility: 0,
        previewPath: "C:/Users/flomu/Downloads/Reticles/Dropoff.png",
        contentPath: "C:/Users/flomu/Downloads/Reticles/Dropoff.png",
      })
```

It seems to fail to update the workshop item, and returns the error: 
`[Error: access denied] { code: 'GenericFailure' }`

I'm able to update an item fine when not setting the previewPath and contentPath, so it must be related to that.

**Comment by arepp23** [comment]
I have also tried with double backslashes in the paths.

**Comment by ceifa** [comment]
This "GenericFailure" can be a lot of things from steam side. This is probably not related to steamworks.js.
A suggestion: Try using node to fix your path, like with "path.join"

**Comment by arepp23** [comment]
Do you have any suggestions on debugging this issue? `path.join` or `path.resolve` just return the string I was already using.

**Comment by arepp23** [comment]
Wow this took me so long to figure out- in the partner.steamgames.com Steamworks settings page for your app you must go to Application -> Steam Cloud and enable files and byte quota for your game before you can use the API to create items. This is very confusing because the API will actually let you make items, but you can't edit them and upload content without this setting turned on: 

![image](https://github.com/ceifa/steamworks.js/assets/53490143/11d6b9be-3cd8-4bbe-8c40-7597e93cbb13)
