### ISSUE TITLE
Feature request: implement GetSubscribedItems

### ISSUE THREAD

**Issue by arepp23** [ceifa/steamworks.js#109]
Implementing [GetSubscribedItems](https://partner.steamgames.com/doc/api/ISteamUGC#GetSubscribedItems) would allow for a more complete Workshop integration. Without this it's only possible to write workshop items, but not to read installed workshop items. Implementing this would allow the app using Steamworks.js to get all the users subscribed items, so it can then call `installInfo` on each to interact with the content.

**Comment by ceifa** [comment]
Just released it on 0.2.2! :tada:
