### ISSUE TITLE
Feature request: implement CreateQueryUGCDetailsRequest

### ISSUE THREAD

**Issue by arepp23** [ceifa/steamworks.js#110]
Implementing [CreateQueryUGCDetailsRequest](https://partner.steamgames.com/doc/api/ISteamUGC#CreateQueryUGCDetailsRequest) would further enhance the Workshop integration as it would allow for getting metadata (like title, description, author) about subscribed workshop items.

**Comment by ceifa** [comment]
available on 0.3.0!
