### ISSUE TITLE
Is Steam overlay possible with the current Electron version?

### ISSUE THREAD

**Issue by infidel-** [ceifa/steamworks.js#12]
```
app.commandLine.appendSwitch('in-process-gpu')
app.commandLine.appendSwitch('disable-direct-composition')
```
I don't see these in the Electron documentation.

**Comment by ceifa** [comment]
What exactly you don't see? AFAIK these command line arguments are not specific to electron, they are for the chrome.
Steamworks.js works in any version of electron above 12.

**Comment by infidel-** [comment]
Oh, that explains it, then. I was looking for them in Electron documentation. Anyway, now I've tested it and it works. Thanks for your help.
