### ISSUE TITLE
On require of steamworks.js, receiving Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by goosehub** [ceifa/steamworks.js#126]
I am using Windows `x64`, Electron `2.0.18`, Vue.js `2.6.11`, Node `12.22.0`, NPM `6.14.6`

I have ran `npm i steamworks.js` successfully. I've added `webPreferences` section to the `BrowserWindow` config. From there my application still works without issue. Whenever I require steamworks.js, I receive the following error.

```Uncaught Error: Module did not self-register.```

This error is thrown when I do `require('steamworks.js')`, as well as when I try `import steamworks from 'steamworks.js'`.

The error appears to be a failure of `steamworksjs.win32-x64-msvc.node` to load. Some research suggests this could indicate a missing dependent dll, but I'm not sure. `lucasg/Dependencies` doesn't show any missing dll dependencies. This is a binary file so I can't troubleshoot the error message any further that that.

In attempts to get it working, I have run `npm install`, `npm rebuild`, `npm cache clean --force`, manually rebuilding the `node_modules` folder, and using `electron-rebuild`. I've also tried adding `sdkencryptedappticket64.dll`, and `sdkencryptedappticket64.lib` to the win64 folder as that was needed greenworks, but no change. I also installed `vc_redist.x64.exe` and `vc_redist.x8.exe`.

This is the same error message as #75 but none of the solutions in that issue fixes the issue for me. Also unlike those users I'm not using electron forge and my dependency walker isn't showing `steam_api64.dll` missing. To be certain I unpacked asar and confirmed the files were there.

I'm very excited that this project exists as it seems more promising than the many days I've spent attempting other existing options, but I'm stuck on this error message. Please let me know what I should do or check to make progress on getting this running. Much appreciated!

Full trace:

```
ELECTRON_ASAR.js:166 Uncaught Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\www\merchant\node_modules\steamworks.js\index.js:8:21)
    at Object.<anonymous> (C:\www\merchant\node_modules\steamworks.js\index.js:78:3)
```

**Comment by LZQCN** [comment]
In fact, if you are using electron forge, it will automatically exclude the DLL from asar and copy the DLL to the correct location. If you are not using electron forge, you will need to manually copy the DLL file to the correct location or disable the asar option.

**Comment by goosehub** [comment]
>you will need to manually copy the DLL file to the correct location
Thanks for the reply. To be clear, which DLL file and which location? `steam_api64.dll` is in `node_modules\steamworks.js\dist\win64` and when I unpack asar I see that file included as expected. Also, setting `asar: false,` in `build.config.js` still results in receiving the same error message. I'm using `electron-packager`.

**Comment by LZQCN** [comment]
Maybe the issue you encountered is not related to DLL files.
Some information indicates that the `Uncaught Error: Module did not self-register.` may be related to an inconsistent ABI version. Make sure the ABI version matches the required version for the application. Use `process.versions.modules` to obtain the current ABI version and verify if it is consistent with the ABI version required by the application. If they don't match, it may be necessary to update or upgrade the related libraries or dependencies.

**Comment by goosehub** [comment]
`process.versions.modules` outputs `57`.  Unfortunately I'm not familiar with ABI's, but I do have nodeAbi, so I ran the following.

```

When you say check required version for the application, do you mean steamworks.js, or electron-packager, or something else? Not sure where that info can be found.

**Comment by ceifa** [comment]
Node 12 and electron 2 are too old. Is it possible to try on node 14 and electron 12+?

**Comment by LZQCN** [comment]
electron 2 are too old. latest version is 28.1.3.

**Comment by goosehub** [comment]
> Node 12 and electron 2 are too old. Is it possible to try on node 14 and electron 12+?
I wasn't able to upgrade all the way to electron 12+ because of issues with depending on `simulatedGREG/electron-vue:`, but upgrading to electron 4 works with both that project and this one. Thank you your help and for creating this awesome project!
