### ISSUE TITLE
steamworks shutdown

### ISSUE THREAD

**Issue by arturbodilki** [ceifa/steamworks.js#128]
Hello pls, my english not good, how shutdown steamworks. please very help serious!

**Comment by arturbodilki** [comment]
@ceifa

**Comment by LZQCN** [comment]
You can describe the problem clearly in your native language first. Currently, the information you provided is too limited for us to understand what exactly happened and offer further assistance.

**Comment by ceifa** [comment]
Hey @arturbodilki, closing this for now. Hope you can provide more info for us to help you.
