### ISSUE TITLE
getAuthTicketForWebApi missing in package

### ISSUE THREAD

**Issue by KlutzyBubbles** [ceifa/steamworks.js#139]
when adding `0.3.1` with `npm install steamworks.js`, the client.d.ts file is missing `getAuthTicketForWebApi` even though its present in this repo.

Haven't tested if the function is actually there and the declaration just hasn't been updated but it still seems like an issue to raise

**Comment by SmoshySmosh** [comment]
@ceifa Can you please release a new version of the package?

**Comment by maoweifan** [comment]
0.3.1 on npmjs is missing this API
`console.log(client.auth.getAuthTicketForWebApi);` => `undefined`

**Comment by LZQCN** [comment]
@KlutzyBubbles @SmoshySmosh 
This fork package [@ai-zen/steamworks.js](https://www.npmjs.com/package/@ai-zen/steamworks.js) contains the latest changes.

**Comment by ceifa** [comment]
Thanks for reporting this @KlutzyBubbles. I will look at the PRs and release a new fixed version.

**Comment by britg** [comment]
Hello, friendly bump here on this issue. I'm looking to use this `getAuthTicketForWebApi`. Please let me know if I can contribute any assistance, but it looks like everything is implemented, it's just not exposed to javascript.

**Comment by ceifa** [comment]
Fixed in 0.3.2 🎉
