### ISSUE TITLE
Building for all targets

### ISSUE THREAD

**Issue by nergmada** [ceifa/steamworks.js#14]
Hi there,

Love the project, so glad to see an API for Steamworks SDK for JavaScript - absolutely saved my life. 

I'm trying to implement AuthTickets (I have a game that uses a remote server). I think I can implement it pretty easily (and I'm happy to put in a PR once it's done), but I wanted to ask how you build for all targets?

I can see the build puts a .node file out into /dist, but mine only does Linux, do I need to do it on all three platforms?

TIA

**Comment by ceifa** [comment]
AFAIK there is no way to build for all targets easily.
The good news is that you don't need to. You can develop and test on your current target, and open a PR. When the code is merged to `main`, a github action will build for all targets and publish a new version.

**Comment by framerate** [comment]
@nergmada Is it the equivalent of `greenworks.getAuthSessionTicket(handler, errorHandler)` you're wanting to implement (if you came from greenworks)

**Comment by framerate** [comment]
Great! Time for me to start playing with this!
