### ISSUE TITLE
Check Achievement

### ISSUE THREAD

**Issue by michaelpelletier** [ceifa/steamworks.js#15]
`client.achievement.activate('ACHIEVEMENT')` seems to return true even if the achievement was previously activated. It would be awesome if this either a) had a way of only returning true if the achievement was _newly_ activated, or if b) there was a way to check beforehand if the achievement had already been obtained.

**Comment by ceifa** [comment]
I added an `client.achievement.is_activated` in `0.0.17` https://github.com/ceifa/steamworks.js/commit/f623ac5b5f767406e52a0876b25af47446b84648
