### ISSUE TITLE
Auth API

### ISSUE THREAD

**Issue by oyed** [ceifa/steamworks.js#16]
Is it possible to use the Steamworks Auth API (Session Tickets)? Couldn't find anything here for it yet

https://partner.steamgames.com/doc/features/auth#client_to_backend_webapi

**Comment by oyed** [comment]
Should just be a case of exposing these to NAPI: https://github.com/Noxime/steamworks-rs/blob/master/src/user.rs#L33

I'd help but I'm not a Rust user and have no idea how to work with the callbacks mentioned (See: https://github.com/Noxime/steamworks-rs/blob/master/src/user.rs#L27)

@ceifa You should consider enabling Sponsorships - I'd be happy to contribute as thanks for creating this awesome lib!

**Comment by ceifa** [comment]
This is great to hear! I love open source but I don't have much time for it, so I usually just work on things I'm going to use, maybe some sponsorship would be nice to start making things for the community.

I will take a look on that and try to enable it, thanks for it :)

**Comment by oyed** [comment]
@ceifa No problem! :)

If you could answer a quick question for me, I could PR this functionality in; the callbacks mentioned here (https://github.com/Noxime/steamworks-rs/blob/master/src/user.rs#L27), are they something I'd need to implement? I would be using this via the Steamworks Web API, so presumably yes, and how would I go about implementing the callback functionality? Don't worry if that's too much

Thanks again!

**Comment by ceifa** [comment]
Needed to implement: https://github.com/Noxime/steamworks-rs/pull/99

**Comment by ceifa** [comment]
Added in `0.0.17` https://github.com/ceifa/steamworks.js/commit/53b85e3f9c346166feff21141f0208ede391be47
