### ISSUE TITLE
`.init()` works on initial load, but not on subsequent reloads

### ISSUE THREAD

**Issue by Jazcash** [ceifa/steamworks.js#22]
I'm calling `steamworks.init(480)` in the renderer, and it works fine on first load, but then when reloading the window it calls that again and I get the error:

```
Uncaught (in promise) Error: Client already initialized for app id 480
```

Even if I put a huge timeout here, it still errors. Works fine in main process btw.

**Comment by ceifa** [comment]
Introduced in commit b8420a329859081978bde4e5a89f19f79fa0cfdb

**Comment by ceifa** [comment]
Tbh I don't remember anymore why I did this change. But other clients do it too: https://github.com/Facepunch/Facepunch.Steamworks/blob/5cb1496e80ce9cd0c6b31155d3dbd92838d10cc1/Facepunch.Steamworks/SteamClient.cs#L21

**Comment by dfabulich** [comment]
AFAIK it should be legal to `init` multiple times, and it seems impossible to _prevent_ it when reloading the window. Would you approve a PR to remove that error?

**Comment by latenightgames** [comment]
Shouldn't that only be called in the main process though? Best practice is to have all this run in the main process and talk to it via IPC.

**Comment by dfabulich** [comment]
I'd been using greenworks on the renderer process and it works fine.

**Comment by dfabulich** [comment]
If the plan is to only use steamworks on the main process, that should be documented somewhere.

**Comment by latenightgames** [comment]
> I'd been using greenworks on the renderer process and it works fine.

I also used to do this, and every time it could give a warning not to do it (running non-context aware modules in the render process will be depreciated, etc). I'm not sure if the same problems will arise with Steamworks.js ever, but once I switched to the "everything in main" way life became much, much simpler. It's easy to set up and secure -- you can set up the methods you need from the IPC module to be available in the render process in your preload script and then control the commands that are sent through them. Then all you need is a listen in main that responds with whatever info you need.

The net result is that I don't include any Node.js or Electron specific stuff in my render process at all. If I need the Steam ID, for example, it's just:

`const steamData=ipc.sendSync('greenworks',{request:'getSteamId'});`

(I'm still on Greenworks but I'm planning to switch when I have time.)

**Comment by ceifa** [comment]
This will be fixed in the next release

**Comment by ceifa** [comment]
About using steamworks on the renderer process, it is indeed more insecure than using IPC with the main process, but if you have a whole controlled environment, it's not something you should worry about.

**Comment by latenightgames** [comment]
I'd argue that "everything in main" is still a good practice, even if it's only for good habits, code portability and to make your life easier in the long run. This is a really thorough article on preload, context isolation and security in Electron, in case anyone's interested in a deeper read; https://www.debugandrelease.com/the-ultimate-electron-guide/
