### ISSUE TITLE
Steam Overlay only works when devtools is open

### ISSUE THREAD

**Issue by Jazcash** [ceifa/steamworks.js#23]
In my main process I'm doing:

```js
app.commandLine.appendSwitch("in-process-gpu");
app.commandLine.appendSwitch("disable-direct-composition");

const client = steamworks.init(480);
```

And in my render process I have:

```js
// this is required for Steam Overlay to render smoothly
function tick() {
    console.log("tick");
    requestAnimationFrame(() => tick());
}
tick();
```

But when devtools is closed, the overlay doesn't show at all, and when devtools is open, it shows and looks ok, but I can't see the game behind it and pressing Shift+Tab again switches focus to devtools and it isn't possible to return to the main browser view. This suggests to me that devtools possibly has its own process/window that the overlay is attaching to. Any ideas?

**Comment by Jazcash** [comment]
Actually I've just figured it out, but it's a bit funky...

The reason it was attaching to the console before, was because of the `console.log("tick");`.

If I render something on the page every tick instead, then the overlay works perfectly:

[ice_video_20220904-130754.webm](https://user-images.githubusercontent.com/1434248/188312691-6839742f-1c82-4680-a7ec-bf0e1252cf70.webm)

**Comment by ceifa** [comment]
Yep, something like that is still needed :/
In a near future I would like to create a function like `electronFixOverlay` which make all these configurations.
