### ISSUE TITLE
API doesn't match steamworks-rs or C++ API; hard to find documentation

### ISSUE THREAD

**Issue by dfabulich** [ceifa/steamworks.js#34]
`steamworks.js`'s API doesn't match the API of `steamworks-rs` or the official Steamworks C++ API. As a result, it's kinda hard to track down documentation for individual methods.

For example, `client.cloud.readFile` is in a `cloud` package, but the Steamworks API refers to it as "ISteamRemoteStorage", and `steamworks-rs` puts it in a struct called `RemoteStorage`. So if you know you want the "remote storage" functions, you just have to figure out that in `steamworks.js`, that means the `cloud` package.

Furthermore, `cloud.readFile` has no documentation, and `steamworks-rs` doesn't have a simple `read_file` function. As a result, the only way to learn what `readFile` does is to read `cloud.rs`, comparing and contrasting that with https://docs.rs/steamworks/latest/steamworks/struct.SteamFileReader.html#method.read_to_string and thinking about how that might correspond to https://partner.steamgames.com/doc/api/ISteamRemoteStorage#FileReadAsync

I think at least the exposed modules should map one-to-one with the modules of `steamworks-rs`, so, e.g. `cloud.rs` should be `remote_storage.rs`, and each function should either have hand-written documentation or should link to the documentation on https://docs.rs/steamworks/latest/steamworks/

**Comment by dfabulich** [comment]
That would mean, for example:

```
auth -> user
cloud -> remoteStorage
stats -> userStats
achievement -> userStats
localplayer -> friends, user, utils
```

**Comment by ceifa** [comment]
My idea was make it simpler to consume and not fully tied to the original steamworks API, which is not thought to be consumed in Javascript. But you are probably right, newcomers can find it difficult because of the difference with the official steamworks docs.
