### ISSUE TITLE
Support inviting steam friends

### ISSUE THREAD

**Issue by adrianmarple** [ceifa/steamworks.js#40]
It would great to be able to allow players to invite their steam friends to play with them. As far as I can tell this requires the following steam API calls:

- ISteamMatchmaking.CreateLobby
- ISteamFriends.ActivateGameOverlayInviteDialog
- ISteamMatchmaking.JoinLobby
- Various Lobby callbacks:
  - LobbyCreate_t
  - LobbyEnter_t
  - LobbyInvite_t
  - LobbyDataUpdate_t

I suspect this is an incomplete list since I haven't implemented this in another system and it is one of more complex interactions with the Steam SDK.

**Comment by ceifa** [comment]
Related https://github.com/Noxime/steamworks-rs/pull/112

**Comment by ceifa** [comment]
Will be available on the next release

**Comment by adrianmarple** [comment]
Thanks for the update! It's mostly working for me. I forgot to mention one of the most important callbacks: [ISteamFriends::GameLobbyJoinRequested_t](https://partner.steamgames.com/doc/api/ISteamFriends#GameLobbyJoinRequested_t)
This gets called when you accept an invite and the game is already open.
The case where the game is opened by steam from an invite works though.

Also the code has `matchmaking.joinJobby` with a "J" instead of `matchmaking.joinLobby` with an "L".

Again thanks so much for working on this ceifa!

**Comment by adrianmarple** [comment]
As an alternative to using the steam invite dialog, my game in particular only needs a list of steam friends' IDs since it's got its own database. So implementing some of the ISteamFriends apis (in particular GetFriendByIndex and GetFriendCount) would be useful for me at least.

**Comment by ceifa** [comment]
Hey @adrianmarple!

Just added the [ISteamFriends::GameLobbyJoinRequested_t](https://partner.steamgames.com/doc/api/ISteamFriends#GameLobbyJoinRequested_t), it will be available on next version.
For other requests, open a new issue, so we don't overflow the repo with infinite old issues.
