### ISSUE TITLE
Feature request: add `MicroTxnAuthorizationResponse_t` to callbacks

### ISSUE THREAD

**Issue by kkortes** [ceifa/steamworks.js#48]
As discuss on Discord earlier this year I would love it if `callback.SteamCallback` also includes `MicroTxnAuthorizationResponse_t` to allow developers of steamworks.js to automatically complete authorized purchases made via the Steam overlay.

https://partner.steamgames.com/doc/api/ISteamUser

In-app must be initialized through your own backend (this cannot be implemented through Steamworks SDK). More on that here: https://steamcommunity.com/dev

I already have this set up for my game (https://worldseed.eu). Without `MicroTxnAuthorizationResponse_t` I must optimistically guess that a initiated purchase went through and provide the user with a button to manually call `FinalizeTxn`: https://partner.steamgames.com/doc/webapi/ISteamMicroTxn

**Comment by gpronet** [comment]
We have the same problem. I know it is not desirable, but as workaround has anyone attempted to call FinalizeTxn periodically (every few seconds) from the server in order to complete the purchase automatically? Having a button for this just seems like a very bad solution.

**Comment by ceifa** [comment]
Added on `0.1.0` version
