### ISSUE TITLE
How can I get actionSetName?

### ISSUE THREAD

**Issue by joey2217** [ceifa/steamworks.js#53]
```ts
export namespace input {
  ...
  export function getActionSet(actionSetName: string): bigint
  ...
}
```

How can I get getActionSet's param  actionSetName?

**Comment by ceifa** [comment]
You should set the action set name on your actions file. Please refer to the oficial steamworks documentation to understand how ISteamInput works: https://partner.steamgames.com/doc/features/steam_controller
