### ISSUE TITLE
Shut down client (detach)

### ISSUE THREAD

**Issue by TheOftedal** [ceifa/steamworks.js#54]
First off I want to thank all the contributors for this awesome project! 🔥 

I am working on a project were I have to be able to initialize and gracefully shut down the steamworks client during different lifecycles of my app (Electron). Lazy initialization of the client works as expected, but I am unable to see a way to call the internal shutdown function to gracefully detach from the steam process without closing the app.

I see that there is a gc (drop) function in the `steamworks-rs` package this project is using, but I see no way of triggering this from JS.

Any help would be appreciated! 😺

**Comment by ceifa** [comment]
@TheOftedal did you manage to make it shutdown?
