### ISSUE TITLE
Feature request: get app install dir

### ISSUE THREAD

**Issue by zzmingo** [ceifa/steamworks.js#6]
This is a cool library, and I am going to use this in my game based on electron.
I want a feature is to get the installation directory of the current app.

**Comment by framerate** [comment]
@zzmingo isn't that part of electron's API, not something steamworks would do?
```
app.getAppPath()
```
Might do what you need!

https://www.electronjs.org/docs/latest/api/app#appgetapppath

**Comment by dfabulich** [comment]
Surprisingly, it _is_ something that Steamworks handles, as part of its `ISteamApps` interface.

https://partner.steamgames.com/doc/api/ISteamApps#GetAppInstallDir

I filed #25 to request support for ISteamApps.
