### ISSUE TITLE
Accuracy loss

### ISSUE THREAD

**Issue by whaqzhzd** [ceifa/steamworks.js#60]
hi, since the type defined in [Dependency Library](https://github.com/Noxime/steamworks-rs/blob/master/src/matchmaking.rs#L348) is LobbyId/SteamId, when we register the callback, the value is returned by Is there any good way to get the correct value?

**Comment by whaqzhzd** [comment]
尝试使用[matchmaking.js](https://github.com/ceifa/steamworks.js/blob/main/test/matchmaking.js#L5)
会发现
![image](https://user-images.githubusercontent.com/16913061/211143608-b862434a-46f9-497b-bc2f-a5f951d99541.png)

![image](https://user-images.githubusercontent.com/16913061/211143630-d886b826-d49f-4962-b230-31310d98b701.png)

**Comment by whaqzhzd** [comment]
I'm doing it the dumb way, defining the type on the steamworks.js side to match the type on the steamworks.rs side, and then defining the type and conversion manually

**Comment by whaqzhzd** [comment]
Since I forked the library messed up a lot of changes, if this is a good solution, I can submit a pure pr if needed

**Comment by ceifa** [comment]
Why did you close the issue @whaqzhzd ?

**Comment by whaqzhzd** [comment]
sorry, I thought you had your own solution to this problem and closed him

**Comment by ceifa** [comment]
Checked with @Brooooooklyn and it seems like a bug on https://github.com/napi-rs/napi-rs/blob/main/crates/napi/src/js_values/ser.rs

**Comment by ceifa** [comment]
Fixed, will be available on the next version of steamworks.js

**Comment by ceifa** [comment]
@whaqzhzd I can see your fork have some great work, maybe you can share some with us in PRs 🥺

**Comment by whaqzhzd** [comment]
@ceifa sure, I'd love to, but I don't really know what part you mean by good part, do you mean the p2p part, I modified a lot of steamworks-rs code in this part, if so, I need to submit the code to steamworks-rs first, and only after the merge I can continue to submit the code on steamworks-js

**Comment by ceifa** [comment]
@whaqzhzd tbh I didn't understand a thing of the p2p code hahah. I'm not familiar with networking logic, why the current implementation of `networking` is not enough?

**Comment by ceifa** [comment]
I see! Very cool. I think you should open PRs on `steamworks-rs` and `steamworks.js` with these cool features, it would be a great addition!

**Comment by MikalDev** [comment]
Agree about the new networking interface, I was getting up to speed on rust, just to look at implementing this interface in both crates. Nice work!
