### ISSUE TITLE
Testing using contextIsolation = true for Electron

### ISSUE THREAD

**Issue by MikalDev** [ceifa/steamworks.js#62]
What I have done so far:

in index.js: 
```js
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      preload: path.join(__dirname, 'preload.js'),
    },
})
```

in preload.js:
```js
const steamworks = require('steamworks.js')
const { contextBridge } = require('electron')
contextBridge.exposeInMainWorld('steamworks', steamworks)
```

Other files in the renderer thread can then reference the 'steamworks' object.

This is working so far in Electron on MacOS with some simple functions, init, setting/clearing achievements (though MacOS does not support Electron/Steam overlay, so I have not tested that yet, will test it later on a Windows dev system.) Anyone have experience with this yet?

**Comment by ceifa** [comment]
I do exactly that on my game and it works great, on all platforms.
