### ISSUE TITLE
Is there a minimal example project?

### ISSUE THREAD

**Issue by qq253498229** [ceifa/steamworks.js#67]
I'm using Angular+electron+steamworks.js, and I've been trying for a long time, but it doesn't work properly. 
The furthest I can get is the steam community overlay popping up on the page, but the mask doesn't refresh in real time, and finally when I package it as a desktop application, it doesn't work and throws an exception.

Is there a sample project I can refer to?

**Comment by ceifa** [comment]
Not exactly with this stack, but we have a minimal example with electron here: https://github.com/ceifa/steamworks.js/tree/main/test/electron

**Comment by ceifa** [comment]
There are some people using steamworks.js in open source projects, you can search for some project using angular too: https://github.com/ceifa/steamworks.js/network/dependents
