### ISSUE TITLE
How to set achievement?

### ISSUE THREAD

**Issue by mikekrow** [ceifa/steamworks.js#70]
client.achievement.activate('ACHIEVEMENT') does not seem to actually set the achievement as true. 
I'm using the achievement ID set up in steam but when I run it but still it results in a FALSE.

Is there actually a working example? I have checked other projects using steamworks.js and none actually seem to use client.achievement. 

I have also noticed I'm getting this message at start up and wonder if there is a connection.
```
Setting breakpad minidump AppID = myappid
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  mysteaid [API loaded no]
```

But I am still able to get my playername via client.localplayer.getName() so I'm not sure if the "[API loaded no]"  mean anything or not.

**Comment by proluk** [comment]
Hey i've also had problems with setting achievements, but managed to make it work. I also have this [Api loaded no] but it still works.

Do not know exactly how you setting this up but if anyone will be setting up electron with ipc, this might help

_preload.ts_
```
const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('integration', {
    addAchievement: (id: string) => ipcRenderer.invoke('addAchievement', id),
    isAchievementActive: (id: string) => ipcRenderer.invoke('isAchievementActive', id)
})
```
_webPreferences while creating window_
```
    webPreferences: {
      devTools: true,
      contextIsolation: true,
      nodeIntegration: true,
      preload: path.join(PATH_TO_YOUR_PRELOAD_FILE)
    }
```

_in my index.ts after creating window, and before loading html_
```
try {
    const client = steamworks?.init(YOUR_APP_ID)
  
    console.log('steamworks',client)

    steamworks?.electronEnableSteamOverlay();

    ipcMain.handle('addAchievement', (event, id: string) => {
      console.log('addAchievement', id)
      const result = client.achievement.activate(id);
      console.log('addAchievement result', result)
      return result;
    })
    ipcMain.handle('isAchievementActive', (event, id: string) => {
      console.log('isAchievementActive', id)
      const result = client.achievement.isActivated(id)
      console.log('isAchievementActive result', result)
      return result;
    })

  } catch {

  }
```

running `window.integration.addAchievement(YOUR_ACHIEVEMENT_ID)` in my _index.html_ shows overlay with achievement unlocked

**Remember that steam must be running!**

If you have some questions, feel free to ask.
