### ISSUE TITLE
Tauri integration

### ISSUE THREAD

**Issue by antharuu** [ceifa/steamworks.js#71]
Currently, steamworks.js only works with Electron for desktop applications. However, Tauri is an interesting alternative to Electron that offers improved security and a smaller package size. So we would like to propose an application to integrate Tauri with steamworks.js.

Tauri is a platform for building cross-platform desktop applications using web technologies such as Rust, HTML, CSS and JavaScript. It offers a secure environment by default, with sandboxing and a strong security policy. In addition, Tauri generates smaller binaries than those generated by Electron, which can be an advantage for developers looking to optimize the size of their application.

I understand that this integration may require significant changes to the steamworks.js code, but I think it's worth exploring this possibility. So I would like to ask the steamworks.js developers to look into the possibility of integrating Tauri for desktop applications.

I hope you will take this request into consideration and consider Tauri integration for desktop applications.

**Comment by real2two** [comment]
+1

**Comment by DrummerSi** [comment]
Tauri integration would require a complete re-write in a different language, as I believe Tauri utilises a Rust backend, not Node... Essentially you'd have to port this project to a new one

**Comment by arthuro555** [comment]
You can already use [steamworks-rs](https://github.com/Noxime/steamworks-rs), which is what this library is based on. It'd likely be more idiomatic Tauri to do native things in rust land than in js anyways.
