### ISSUE TITLE
Feature Request: Utils

### ISSUE THREAD

**Issue by dfabulich** [ceifa/steamworks.js#76]
https://partner.steamgames.com/doc/api/ISteamUtils has a bunch of random useful functions, which appear in https://docs.rs/steamworks/latest/steamworks/struct.Utils.html

Today, I'm particularly interested in the Steam Deck utilities, which were merged into https://github.com/Noxime/steamworks-rs/pull/119

**Comment by dfabulich** [comment]
That PR merged Feb 19, 2023, but, as I write this, steamworks-rs hasn't had a new release since version 0.9.0 in April 2022. 😳 I hope they release a new version soon, and that steamworks.js consumes it and exposes these functions.

**Comment by ceifa** [comment]
`steamworks.js` is not tied to a specific version of `steamworks-rs`: https://github.com/ceifa/steamworks.js/blob/main/Cargo.toml
Because we are using the git version, it is already possible to implement these functions, PRs welcome!
