### ISSUE TITLE
Feature Request: Activate Steam overlay

### ISSUE THREAD

**Issue by dfabulich** [ceifa/steamworks.js#79]
It would be great if steamworks.js would expose `activate_game_overlay` and `activate_game_overlay_to_web_page` from `steamworks-rs`.

https://docs.rs/steamworks/latest/steamworks/struct.Friends.html

**Comment by dfabulich** [comment]
There's code in the readme about how to get the Steam overlay to work. (`electronEnableSteamOverlay`)

But… what's the point of that code, if you can't activate an overlay?

**Comment by dfabulich** [comment]
See also https://github.com/Noxime/steamworks-rs/issues/126 

> steamworks-rs is missing these Activate Overlay features from ISteamFriends:
> 
> * ActivateGameOverlayToStore
> * ActivateGameOverlayToUser

**Comment by ceifa** [comment]
> But… what's the point of that code, if you can't activate an overlay?

Users can activate the overlay manually to, with `Shift + Tab`
