### ISSUE TITLE
Feature Request: add visibility as an option to UgcUpdate

### ISSUE THREAD

**Issue by arepp23** [ceifa/steamworks.js#87]
It would be nice if we could pass in a visibility state to `workshop.updateItem`. 

The current type is like this, it would need a new field for visibility:
```
  export interface UgcUpdate {
    title?: string
    description?: string
    changeNote?: string
    previewPath?: string
    contentPath?: string
    tags?: Array<string>
  }
```

[Docs on ISteamUGC#SetItemVisibility](https://partner.steamgames.com/doc/api/ISteamUGC#SetItemVisibility)

**Comment by ceifa** [comment]
fixed on last version
