### ISSUE TITLE
how to build an assembly in a dist folder

### ISSUE THREAD

**Issue by davit87yeghoyan** [ceifa/steamworks.js#91]
Hello, I have a mac m1, with the command "npm ru build " a file is generated steamworksjs.darwin-x64.node

I have such a question. how to generate a file for windows and for linux?  (steamworksjs.win32-x64-msvc.node  and steamworksjs.linux-x64-gnu.node)

**Comment by cijiugechu** [comment]
This library uses `napi-rs` under the hood, it distributes native addons for different platforms [via different npm packages](https://napi.rs/introduction/release), which means you don't need to build binary by yourself.

**Comment by davit87yeghoyan** [comment]
I created a version for mac x64,

and now I want to create a project for win x64
, how it can be organized, I don't understand

**Comment by ceifa** [comment]
See https://github.com/ceifa/steamworks.js/issues/14
