### ISSUE TITLE
Steamworks SDK v1.5.2 is required for init() to work on darwin x64

### ISSUE THREAD

**Issue by JamesMoulang** [ceifa/steamworks.js#93]
On an intel mac (macOS v12.0.1), the latest version of steamworks.js freezes when I call `init`. No error message is shown, the entire app freezes.

The specific command seems to be `internalInit(appId)` based on some debugging with `console.log`

I tried re-building `steamworksjs.darwin-x64.node` (which I can see that steamworks.js is using) from source, and had the same issue.

I was able to fix this problem by either:
- Running the code on an M1 macbook
- Downloading steamworks SDK 1.5.2 and replacing it with the version in `dist/osx/`

**Comment by ceifa** [comment]
updated to 1.54
