### ISSUE TITLE
Steam Overlay not working at all

### ISSUE THREAD

**Issue by dfabulich** [ceifa/steamworks.js#97]
To reproduce:

1. On Windows, clone the steamworks.js github, launch Steam, and login.
2. `npm install`
3. `npm run build`
4. `cd test`
5. `cd electron`
6. `npm install`
7. `npm start`. The Electron app will open, and display your Steam display name.

    But it will _not_ show the Steam Overlay hint, which normally looks like this:

   <img src="https://github.com/ceifa/steamworks.js/assets/96150/55a575a1-cbbb-4b42-9f5e-0eb75c992f3c" width="240">

8. Try pressing Shift-Tab. Nothing happens; no overlay appears.
9. Edit `index.html` and add this button on line 14, right before the `<script>` tag:
```
<button id="activateOverlay">activate overlay</button>
```
10. In `renderer.js`, add this code to the end:

```
document.getElementById('activateOverlay').addEventListener('click', function() {
    console.log('clicked');
    client.overlay.activateToWebPage('https://www.example.com/')
    console.log('done');
})
```
11. Quit and reopen the Electron app, toggle Dev Tools open, and click the "activate overlay" button.

Expected: The overlay should appear immediately at launch with the Shift-Tab hint, and it should fully activate the overlay when you click the "activate overlay" button.

Actual: No overlay appears at all. The Dev Tools console shows log entries, "clicked," and "done" but it doesn't show the overlay.

I've tested this on:

* Windows 11 x64
* Ubuntu 22 x64
* macOS 13 Ventura on aarch64 M1 Apple Silicon

It's hard to be 100% sure, but I've _never_ seen the overlay work; I don't think it ever has worked.

See also #50 and #94. I see your comment https://github.com/ceifa/steamworks.js/issues/50#issuecomment-1299013525 that "it works very well on Linux and Windows," but I've never seen it working on any platform.

**Comment by dfabulich** [comment]
I guess I bear some responsibility for this with #96, but I think that PR just revealed the error.

(And, uh, truth be told, I filed the PR without testing it myself, which is my bad.)

**Comment by dfabulich** [comment]
An easier way to test the overlay is to check out my PR branch in #98, then just click the "activate overlay" button.

**Comment by saintflow47** [comment]
Hey Guys, thanks for all your efforts in this project, it is appreciated a lot!
Sadly, I am in the same boat and cant seem to get the overlay to work up to now. I do have the new Steam installed maybe that changed up things somewhere.
I tried both, electron start and packing the electron app and then adding it as a non steam game to steam and running it like that. steamworks.js initializes, my friends list shows me ingame, but no overlay to be found. I will be happy to further test things if you need any specific things tested ceifa!

**Comment by dfabulich** [comment]
Intriguingly, I'm able to get it to work now, without launching the game from the Steam library, but _only_ on the new client. (I don't know how to revert to the old client to check it.)

I'm going to close this out; I recommend merging #98 to hopefully minimize confusion for other users.
