### ISSUE TITLE
ISteamMicroTxn/InitTxn not Opening Overlay

### ISSUE THREAD

**Issue by saintflow47** [ceifa/steamworks.js#99]
Sorry if this is a feature request instead of an issue, I cannot tell if this should be working or simply isn't a part of steamworks.js yet.

I am currently in the process of working though the Steam Microtransaction Workflow (https://partner.steamgames.com/doc/features/microtransactions/implementation) and after successfully submitting a web request to ISteamMicroTxn/InitTxn the Steam Overlay should automatically open to guide the user through the payment process.

Right now, the request works, the overlay itself works but steamworks does not trigger the overlay or payment process in any way so the process cannot be followed through.

Sadly my knowledge of any flavour of C is very limited so I cannot judge in any way what getting Microtransactions to work in steamworks.js entails. 

I will be happy to pay for a coffee or two if you could have a look into this issue to check if solving it might be possible. Thanks a lot!

**Comment by ceifa** [comment]
Check this example to see it working: https://github.com/ceifa/steamworks.js-microtransaction-example

**Comment by saintflow47** [comment]
Can confirm that the Microtransaction Order Flow is fully working with steamworks.js.
